
 create table order_items (
        id bigint generated by default as identity,
        quantity integer,
        unit_price numeric(38,2),
        primary key (id)
    )

    create table orders (
        id bigint generated by default as identity,
        billing_address varchar(255),
        customer_id bigint,
        date_created timestamp(6),
        last_updated timestamp(6),
        order_items_id bigint,
        status varchar(255),
        total_price numeric(38,2),
        total_quantity integer,
        primary key (id)
    )

    create table product (
        id bigint generated by default as identity,
        active boolean,
        date_created timestamp(6),
        description varchar(255),
        image_url varchar(255),
        last_updated timestamp(6),
        name varchar(255) not null,
        unit_price numeric(38,2),
        units_in_stock integer not null,
        primary key (id)
    )


INSERT INTO "ecommerce"."products" ( name, description, image_url, units_in_stock,
unit_price, date_created)
VALUES ('BOOK-TECH-1001', 'Spring',
'assets/images/products/placeholder.png'
,100,29.99, NOW());

INSERT INTO "ecommerce"."products" (sku, name, description, image_url, active, units_in_stock,
unit_price, date_created)
VALUES ('BOOK-TECH-1002', 'Kubernetes',
'assets/images/products/placeholder.png'
,100,24.99, NOW());

INSERT INTO "ecommerce"."products" (sku, name, description, image_url, active, units_in_stock,
unit_price, date_created)
VALUES ('BOOK-TECH-1003', 'IoT',
'assets/images/products/placeholder.png'
,30,29.99, NOW());

INSERT INTO "ecommerce"."products" (name, description, image_url, active, units_in_stock,
unit_price, date_created)
VALUES ('BOOK-TECH-1004', 'Go',
'assets/images/products/placeholder.png'
,10,24.99, NOW());

