version: "3.8"

services:
  postgresDB:
    container_name: postgresDB
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgres

  teamviewer-ecommerce-application:
    container_name: teamviewer-ecommerce
    build:
      context: ./
    env_file:
      - ./.env
    ports:
      - 8081:8080
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:postgresql://postgresdb:$POSTGRESDB_DOCKER_PORT/$POSTGRESDB_DATABASE",
            "spring.datasource.username" : "$POSTGRESDB_USER",
            "spring.datasource.password" : "$POSTGRESDB_ROOT_PASSWORD",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
    depends_on:
      - postgresDB
    restart: on-failure
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true


volumes:
  db: